### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pewww** [Pewww/snakeeeeeee#1]
- [x] setter, getter 정리
- [ ] 폭탄이 아이템을 완전히 가로막는 경우 방지
- [x] 레벨이 3이 넘어갈 때에 대한 처리
- [x] 모델(Snake, Bomb...)의 공통 추상 클래스 생성 및 하위 클래스에서 구현 - stageSize :(
- [ ] (Optional) 타이머 기능 추가 - 소요 시간(소수점 2자리까지 카운트)
- [x] rotateDegree 이전과 겹치지 않도록
- [x] 메인 화면 (게임 시작 및 How to 버튼) 추가

**Comment by Pewww** [comment]
**코드 리뷰 내용 수정**
- [x] Game 모델을 좀 더 상위 depth로 이동 (src/)
- [x] Bomb의 innerRandomPosition을 for 안으로 + const
- [x] Item에서 Bomb 위치를 알도록 (기존: Bomb에서 Item 위치를 기반으로 position 설정했음)
- [x] Snake 충돌 처리 시 각 모델의 position이 아닌 cell의 타입으로 비교 (연산량 감소)
- [ ] Rotate 제외한 Flip 기능 추가 (Suggestion)
